name: linux-raspberrypi-org
adopt-info: kernel
summary: The Ubuntu generic Linux kernel for Pi4
description: |
  This Ubuntu generic Linux kernel is built for the Raspberry Pi4

grade: stable
confinement: strict
type: kernel
build-base: core18

architectures:
  - build-on: amd64
    run-on: armhf

parts:
  firmware:
    plugin: nil
    source: git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
    source-depth: 1
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/firmware
      cp -av ./* $SNAPCRAFT_PART_INSTALL/firmware/
      cp -av ../../../brcmfmac-firmware/* $SNAPCRAFT_PART_INSTALL/firmware/brcm/
  kernel:
    plugin: kernel
    source: git://kernel.ubuntu.com/ubuntu/ubuntu-eoan.git
    source-type: git
    source-depth: 1
    source-tag: Ubuntu-raspi2-5.3.0-1015.17
    kconfigflavour: raspi2
    kconfigs:
      - CONFIG_DEBUG_INFO=n
      # make graphics work
      - CONFIG_DRM_V3D=m
      # the below allows booting from USB 3.1 SSDs without initrd modules
      - CONFIG_ENCLOSURE_SERVICES=y
      - CONFIG_SCSI_SAS_ATTRS=y
      - CONFIG_USB_STORAGE=y
      - CONFIG_USB_UAS=y
      # required to boot from SD card without having to load modules in initrd
      - CONFIG_REGULATOR_GPIO=y
      - CONFIG_MMC_SDHCI_IPROC=y
    override-pull: |
      snapcraftctl pull
      echo "setting version to $(git tag|sed 's/^Ubuntu-//')"
      snapcraftctl set-version "$(git tag|sed 's/^Ubuntu-//')"
    override-build: |
      cp debian/scripts/retpoline-extract-one \
        $SNAPCRAFT_PART_BUILD/scripts/ubuntu-retpoline-extract-one
      snapcraftctl build
    kernel-with-firmware: false
    build-packages:
      - cpio
      - libssl-dev
      - on amd64 to armhf:
        - gcc-arm-linux-gnueabihf:amd64
    after: [ firmware ]
